/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Root endpoint */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successful response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": string;
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/file/{fileName}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a presigned URL for a file */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The name of the file */
					fileName: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successful response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @description The presigned URL for the file */
							url?: string;
						};
					};
				};
				/** @description File not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": string;
					};
				};
			};
		};
		put?: never;
		/** Create a presigned URL for a new file */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The name of the file to be created */
					fileName: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successful response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @description The presigned URL for uploading the file */
							url?: string;
						};
					};
				};
				/** @description File already exists */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": string;
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: never;
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
